apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: default
  name: nginx
  labels:
    app: nginx
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
